# Generated by Django 4.1.7 on 2023-05-20 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0003_alter_tweet_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="liked_by",
            field=models.ManyToManyField(related_name="liking", to=settings.AUTH_USER_MODEL),
        ),
    ]
